name: Aura Arduino CLI Build
on:
  push:
    branches: [ "main", "feat/24-screen-support-ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    name: build (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ "28_ILI9341", "24_ILI9341", "24_ST7789" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core & libraries
        run: |
          set -euxo pipefail
          arduino-cli core update-index
          # Use latest stable ESP32 core; if you hit toolchain quirks, pin (e.g. esp32:esp32@2.0.17)
          arduino-cli core install esp32:esp32
          # Libraries required by the sketch
          arduino-cli lib install \
            "ArduinoJson@7.4.1" \
            "WiFiManager@2.0.17" \
            "XPT2046_Touchscreen@1.4" \
            "TFT_eSPI@2.5.43" \
            "lvgl@9.2.2"
          arduino-cli lib list

      - name: Provide LVGL config (lv_conf.h)
        run: |
          set -euxo pipefail
          mkdir -p "$HOME/Arduino/libraries/lvgl"
          cp lv_conf.h "$HOME/Arduino/libraries/lvgl/lv_conf.h"
          ls -l "$HOME/Arduino/libraries/lvgl/lv_conf.h"

      - name: Select TFT_eSPI User_Setup for ${{ matrix.target }}
        run: |
          set -euxo pipefail
          mkdir -p "$HOME/Arduino/libraries/TFT_eSPI"
          case "${{ matrix.target }}" in
            28_ILI9341) SRC="TFT_eSPI/User_Setup_AURA_28_ILI9341.h" ;;
            24_ILI9341) SRC="TFT_eSPI/User_Setup_AURA_24_ILI9341.h" ;;
            24_ST7789)  SRC="TFT_eSPI/User_Setup_AURA_24_ST7789.h" ;;
          esac
          # If your files live elsewhere (e.g. config/tft/), update SRC paths above.
          ls -l "$SRC"
          cp "$SRC" "$HOME/Arduino/libraries/TFT_eSPI/User_Setup.h"
          echo "Using $SRC → $HOME/Arduino/libraries/TFT_eSPI/User_Setup.h"

      - name: Compile ${{ matrix.target }}
        run: |
          set -euxo pipefail
          EXTRA_FLAGS=""
          if [ "${{ matrix.target }}" = "24_ILI9341" ]; then EXTRA_FLAGS='-DAURA_SCREEN=24_ILI9341'; fi
          if [ "${{ matrix.target }}" = "24_ST7789" ]; then EXTRA_FLAGS='-DAURA_SCREEN=24_ST7789'; fi
          OUT="out/${{ matrix.target }}"
          mkdir -p "$OUT"
          test -f aura/aura.ino || { echo "::error ::missing aura/aura.ino"; exit 1; }
          arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --board-options PartitionScheme=huge_app \
            --build-property "build.extra_flags=$EXTRA_FLAGS -DLV_CONF_INCLUDE_SIMPLE" \
            --export-binaries \
            --output-dir "$OUT" \
            aura

      - name: Collect artifacts ${{ matrix.target }}
        run: |
          set -euxo pipefail
          OUT="out/${{ matrix.target }}"
          mkdir -p "dist/${{ matrix.target }}"
          # app.bin (sketch), bootloader.bin, partitions.bin from export-binaries
          cp $(find "$OUT" -maxdepth 1 -type f -name "*.bin" ! -name "*partitions*.bin" ! -name "*bootloader*.bin" | head -n1) "dist/${{ matrix.target }}/app.bin"
          cp $(find "$OUT" -maxdepth 1 -type f -name "*bootloader*.bin" | head -n1) "dist/${{ matrix.target }}/bootloader.bin"
          cp $(find "$OUT" -maxdepth 1 -type f -name "*partitions*.bin" | head -n1) "dist/${{ matrix.target }}/partitions.bin"
          # boot_app0 from the ESP32 core
          CORE="$HOME/.arduino15/packages/esp32/hardware/esp32/$(ls $HOME/.arduino15/packages/esp32/hardware/esp32 | tail -n1)"
          cp "$CORE/tools/partitions/boot_app0.bin" "dist/${{ matrix.target }}/boot_app0.bin"
          # Guard: fail if any file is empty
          for f in dist/${{ matrix.target }}/*.bin; do
            [ -s "$f" ] || { echo "::error file=$f::empty bin"; exit 1; }
          done
          ls -lh dist/${{ matrix.target }}

      - name: Upload ${{ matrix.target }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/${{ matrix.target }}
