name: Build Aura (ESP32)

on:
  push:
    branches: [ feat/24-ci-clean ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ "24_ILI9341", "24_ST7789", "28_ILI9341" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.17

      - name: Install libraries
        run: |
          arduino-cli lib install "ArduinoJson@7.4.1"
          arduino-cli lib install "lvgl@9.2.2"
          arduino-cli lib install "TFT_eSPI@2.5.43"
          arduino-cli lib install "XPT2046_Touchscreen@1.4"
          arduino-cli lib install "WiFiManager@2.0.17"

      - name: Compile ${{ matrix.target }}
        run: |
          case "${{ matrix.target }}" in
            "24_ILI9341") EXTRA_FLAGS='-DAURA_SCREEN_24_ILI9341' ;;
            "24_ST7789")  EXTRA_FLAGS='-DAURA_SCREEN_24_ST7789'  ;;
            "28_ILI9341") EXTRA_FLAGS='-DAURA_SCREEN_28_ILI9341' ;;
            *) echo "::error ::Unknown matrix target"; exit 1 ;;
          esac

          OUT="out/${{ matrix.target }}"
          mkdir -p "$OUT"
          test -f aura/aura.ino || { echo "::error ::missing aura/aura.ino"; exit 1; }

          arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --board-options PartitionScheme=huge_app \
            --build-property "build.extra_flags=$EXTRA_FLAGS -DLV_USE_TFT_ESPI=1 -DAURA_ENABLE_WIFI=0 -DLV_CONF_INCLUDE_SIMPLE" \
            --export-binaries \
            --output-dir "$OUT" \
            aura

      - name: Upload ${{ matrix.target }} firmware
        uses: actions/upload-artifact@v4
        with:
          name: aura-${{ matrix.target }}
          path: out/${{ matrix.target }}/*.bin
